version: "3.9"
services:
  app:
    build: ./php
    working_dir: /var/www/html
    volumes: [ "../lavarel:/var/www/html" ]
    env_file: ../lavarel/.env
    depends_on: [ db, redis ]
    networks: [ cnab-net ]

  queue:
    build: ./php
    command: ["bash", "/queue/docker-entrypoint.sh"]
    volumes: [ "../lavarel:/var/www/html", "./queue/docker-entrypoint.sh:/queue/docker-entrypoint.sh" ]
    env_file: ../lavarel/.env
    depends_on: [ db, redis ]
    networks: [ cnab-net ]

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - "../lavarel:/var/www/html:ro"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on: [ app ]
    ports: [ "80:80" ]
    networks: [ cnab-net ]

  redis:
    image: redis:7-alpine
    networks: [ cnab-net ]

  db:
    image: mysql:8.4    
    environment:
      POSTGRES_DB: cnab
      POSTGRES_USER: cnab
      POSTGRES_PASSWORD: secret
    volumes: [ "db-data:/var/lib/mysql" ]
    networks: [ cnab-net ]

networks:
  cnab-net:

volumes:
  db-data:
