services:
  # ───────────────────────── APP (PHP-FPM) ─────────────────────────
  app:
    build:
      context: ../laravel                              # raiz do projeto
      dockerfile: Dockerfile
    volumes:
      - /home/jubarte/PHP_SENIOR_AKRK/backend/docker:/var/www/html               # hot-reload do código
    env_file:
      - /home/jubarte/PHP_SENIOR_AKRK/backend/laravel/.env                        # mesmas variáveis para todos
    depends_on: [db, redis]
    networks: [cnab-net]

    healthcheck:
      test: ["CMD", "php", "-r", "echo 0;"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  # ──────────────────────── QUEUE WORKER ───────────────────────────
  queue:
    build:
      context: ../laravel
      dockerfile: Dockerfile        # reutiliza a mesma imagem
    command: ["start-container", "queue"]
    volumes:
      - /home/jubarte/PHP_SENIOR_AKRK/backend/laravel:/var/www/html
    env_file:
      - /home/jubarte/PHP_SENIOR_AKRK/backend/laravel/.env 
    depends_on:
      app:
        condition: service_healthy
    networks: [cnab-net]
    deploy:
      replicas: 3 
      resources:
        limits:
          memory: 256M   
    restart: unless-stopped                          

  # ─────────────────────────── NGINX ──────────────────────────────
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - /home/jubarte/PHP_SENIOR_AKRK/backend/docker:/var/www/html:ro
      - /home/jubarte/PHP_SENIOR_AKRK/backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [app]
    ports:
      - "80:80"
    networks: [cnab-net]
    restart: unless-stopped

  # ─────────────────────────── REDIS ──────────────────────────────
  redis:
    image: redis:7-alpine
    networks: [cnab-net]

  # ─────────────────────────── MYSQL ──────────────────────────────
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: cnab
      MYSQL_USER: cnab
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /home/jubarte/PHP_SENIOR_AKRK/backend/docker/db-data:/var/lib/mysql
    networks: [cnab-net]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

# ─────────────────────────── NETWORK & VOLUME ─────────────────────
networks:
  cnab-net:

volumes:
  db-data:
